### ISSUE TITLE
Problems with isklad.eu integration

### ISSUE THREAD

**Issue by Horkyze** [paylike/plugin-woocommerce#101]
We are trying to integrate our woocomerce shop with isklad.eu system.
isklad.eu provides a plugin which acts like a back-api to the shop.
During the process of integration (which failed) I stopped on the paylike plugin error, which is weird as I don't see what do these plugins have in common. 

I am willing to hop on a call, to provide further info and assistance. 

```
olivovanie.sk [Fri Mar 18 12:32:16.444321 2022] [php7:error] PHP Fatal error:  
Uncaught Error: Class 'Paylike\\Paylike' not found in web/wp-content/plugins/payment-gateway-via-paylike-for-woocommerce/woocommerce-gateway-paylike.php:159
Stack trace:
#0 web/wp-content/plugins/payment-gateway-via-paylike-for-woocommerce/woocommerce-gateway-paylike.php(203): WC_Paylike->set_secret_key('a9ada013-dc81-4...')
#1 web/wp-content/plugins/payment-gateway-via-paylike-for-woocommerce/woocommerce-gateway-paylike.php(132): WC_Paylike->get_secret_key()
#2 web/wp-includes/class-wp-hook.php(303): WC_Paylike->init('')
#3 web/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#4 web/wp-includes/plugin.php(470): WP_Hook->do_acti in web/wp-content/plugins/payment-gateway-via-paylike-for-woocommerce/woocommerce-gateway-paylike.php on line 159, referer https://www.isklad.eu
```

**Comment by ionutcalara** [comment]
Hi @Horkyze this looks like an issue related to composer. I have updated the way composer autoloader is included to avoid any potential conflict, could you please check the attached version and let me know if you still have the issue? I am asking because I am not able to replicate the issue on my own. 
[woocommerce-gateway-paylike.zip](https://github.com/paylike/plugin-woocommerce/files/8314071/woocommerce-gateway-paylike.zip)

Thank you, 
Ionut

**Comment by Horkyze** [comment]
It's working, thanks for quick fix

**Comment by ionutcalara** [comment]
Thank you for confirming, I will publish the update officially as well. I am closing the issue.
