### ISSUE TITLE
how to implement redirect after payment

### ISSUE THREAD

**Issue by socoolcompany** [paylike/plugin-woocommerce#70]
Just a basic question about the SDK:
Can you help me with the js code to add a redirect url? 
for example, when the customer finishes their payment in the popup window then he will be redirected to www.google.com
How to implement it with modifying the js code? :)

**Comment by ionutcalara** [comment]
Hi @socoolcompany for the woocommerce plugin I am not sure how this will work out, it's not recommended to modify the WooCommerce plugin because you will lose the option of receiving updates. 

If this was a question for the sdk, please add a sample of the code you have and what you would like to achieve here: https://github.com/paylike/sdk/issues/new

If this is for woocommerce, please reopen this issue with a sample of your code and what you want to achieve. 

Please do not post any private information, including your paylike private keys.
