### ISSUE TITLE
3DS verification problem

### ISSUE THREAD

**Issue by rudi-ob** [paylike/plugin-woocommerce#84]
Hi,

After many failed payments since 1st January 2021, I tested the Paylike 3DS verification and found a huge bug.

The Paylike iframe window's height is set to 32em, and because of that the submit button can't be clicked (or even viewed). Also the scrolling is disabled in the iframe.

![paylike-hiba](https://user-images.githubusercontent.com/77856841/105536368-86e51a80-5cf0-11eb-881f-5eaa5780b2b5.jpg)

I just used the following CSS code to solve the problem, but I think there should be an official update with this bug fixed.

```
div.paylike.overlay.tds:not(.full-screen) div.payment form div.tds-iframe iframe {
height: 45em !important;
}
```

**Comment by tjconcept** [comment]
Hi @rudi-ob 

Thanks for filing an issue.

The height of the window is defined by the 3-D Secure v1 specification to be 320px (equivalent to 32em in the popup's CSS). When the button is not visible, it is due to the ACS (the service rendering the framed page) violating this specification.

If you have the most recent version of our WooCommerce plugin, please try checking the "beta" checkbox in the settings page. The newer version of the popup supports the 3-D Secure v2 protocol, which may have higher ACS compliance, but also adds scrolling in cases where ACSs are noncompliant.

I'll close the issue here, but feel free to reopen it if you have further questions.
