### ISSUE TITLE
Orders not created

### ISSUE THREAD

**Issue by Druckermeister** [paylike/plugin-woocommerce#89]
Dear Paylike,

I have a Woocommerce web shop, where your payment gateway is one of the payment options.
Recently, I had 2 transactions:
604bc70dbcae7d1b8e38d255
604e2520bcae7d1b8e38da78
Where the order details were not forwarded back to the shop, so the warehouse workers couldn't see the order.
With the second customer, this is actually a repeating issue (order not created)
She comes back with an order every month, and the order is never created when she pays with Paylike.

Thanks,
Tamás

**Comment by ionutcalara** [comment]
Hi @Druckermeister, sorry to hear about the issue. In this particular case since the paylike popup shows up on the checkout screen, and the order is created after that, anything that might come between the user payment and the order creation would make it so you get this situation. 

The reason might be either a javascript error that prevents the order from being created or some validation that is not properly hooked to the actions that woocommerce offers. 

In order to fix this there are 2 options:
1. Change the checkout mode so that it's set to "Redirect to the payment page after order is created" - this will ask for the payment after, so the popup will not show up on the checkout page. This ensures that any error/validation has to be passed before payment. The downside is this has a lower conversion score, as the payment comes later, and users might create order and not pay it, or in your case, if there's an error they might not submit an order at all, and you wouldn't be able to tell if they do not contact you via support. 
2. You install hotjar.com and sentry.io on the website to detect the issue next time it happens so that you can check what exactly happened and try to replicate the issue. You can also ask the customer if they saw something odd, or try to replicate their order and check if there are any javascript/validation issues. 

I am closing this for now, but feel free to reopen if you have any questions, or you need further clarifications.

**Comment by Druckermeister** [comment]
Hello Ionut,

Option 1. "Redirect to the..." response from the system: "Tokenization is
only compatible with the before order payment mode."

What can I do with this?

Thanks,
Tamás

**Comment by ionutcalara** [comment]
Tokenization refers to saving the credit cards for the user to reuse. If you need that feature, then try to use hotjar and sentry to find out what errors are showing up for the users where the order is not created. Once you are able to replicate the issue then we can look into it.
